name: fake commits

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  fake-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: add todays date
        run: |
          echo $(date) > date.txt
      - name: Commit
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMIT_MSG: |
            COMMITED SOMETHING VERY IMPORTANT
        run: |
          rm -rf geckodriver*
          git config user.email "actions@github"
          git config user.name "Github Actions"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          git pull origin ${GITHUB_REF}
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})
